In [ ]:
#Gauss Jordan
import matplotlib.pyplot as plt
import numpy as np
from prettytable import PrettyTable


def gauss_jordan(matrix, tol, max_iter):
    n = len(matrix)
    x = [0] * n
    errors = []

    table = PrettyTable()
    table.field_names = ["Iterasi", "x1", "x2", "x3", "Error Relatif"]

    for iterasi in range(1, max_iter + 1):
        x_k1 = np.copy(x)
        for i in range(n):
            sum_val = matrix[i][-1]  # Initialize with the constant term
            for j in range(n):
                if j != i:
                    sum_val -= matrix[i][j] * x[j]
            x[i] = sum_val / matrix[i][i]

        error_rel = np.max(
            np.abs(np.array(x) - np.array(x_k1)) / np.abs(np.array(x)))

        table.add_row([iterasi, round(x[0], 4), round(x[1], 4),
                      round(x[2], 4), "{:.4e}".format(error_rel)])

        errors.append(error_rel)

        if error_rel < tol:
            break

    print(table)
    return x, errors


# Matrix of the system of equations coefficients and constants
matrix = [
    [5, 1, 1, 7],
    [1, 5, 1, 7],
    [1, 1, 5, 7]
]

# Parameters
tolerance = 0.0001
max_iterations = 100

# Solve using Gauss-Jordan
solution, errors = gauss_jordan(matrix, tolerance, max_iterations)

# Display the solution
print("\nThe solution for x is:", [round(x, 4) for x in solution])

# Plotting the relative errors
plt.plot(range(1, len(errors) + 1), errors, marker='o')
plt.yscale('log')
plt.xlabel('Iterations')
plt.ylabel('Relative Error')
plt.title('Relative Error in Gauss-Jordan Method')
plt.show()

In [ ]:
#Gauss Seidel
import matplotlib.pyplot as plt
import numpy as np
from prettytable import PrettyTable


def gauss_seidel(m, tol, max_iter):
    x1, x2, x3 = 0, 0, 0
    errors = []

    table = PrettyTable()
    table.field_names = ["Iterasi", "x1", "x2", "x3", "Error Relatif"]

    for iterasi in range(1, max_iter + 1):
        x1_k1 = (1 + m + x2 + x3) / m
        x2_k1 = (2 + m + x1_k1) / m
        x3_k1 = (1 + 1 + m + x1_k1 + x2_k1) / m

        error_rel = np.max(
            np.abs([x1_k1 - x1, x2_k1 - x2, x3_k1 - x3]) / np.abs([x1_k1, x2_k1, x3_k1]))

        table.add_row([iterasi, round(x1_k1, 4), round(x2_k1, 4),
                      round(x3_k1, 4), "{:.4e}".format(error_rel)])

        x1, x2, x3 = x1_k1, x2_k1, x3_k1
        errors.append(error_rel)

        if error_rel < tol:
            break

    print(table)
    return [x1, x2, x3], errors


# Menentukan parameter
m = 5
toleransi = 0.01
max_iterasi = 100

# Menjalankan metode Gauss-Seidel
solusi, errors = gauss_seidel(m, toleransi, max_iterasi)

# Menampilkan hasil
print("\nNilai x yang memenuhi SPL adalah:", [round(x, 4) for x in solusi])

# Membuat grafik error relatif
plt.plot(range(1, len(errors) + 1), errors, marker='o')
plt.yscale('log')
plt.xlabel('Iterasi')
plt.ylabel('Error Relatif')
plt.title('Grafik Error Relatif pada Metode Gauss-Seidel')
plt.show()

In [1]:
import numpy as np
from scipy.linalg import lu, solve


def solve_spl(m):
    # Menentukan nilai m sesuai instruksi
    m = m + 1

    # Matriks koefisien
    A = np.array([[m, 1, 1], [1, m, 1], [1, 1, m]])

    # Vektor hasil
    B = np.array([1 + m + 1, 2 + m, 1 + 1 + m])

    # Dekomposisi LU
    P, L, U = lu(A)

    # Penyelesaian sistem persamaan linear dengan metode substitusi maju dan mundur
    y = solve(L, P.dot(B))
    x = solve(U, y)

    # Menampilkan array matriks A dan vektor B
    print("\nMatriks A:")
    print(A)
    print("\nVektor B:")
    print(B)

    return x


# Menentukan nilai m sesuai instruksi (contoh: m = 3)
m_value = 4

# Memanggil fungsi untuk menyelesaikan SPL
result = solve_spl(m_value)

# Menampilkan hasil
print("\nSolusi SPL:")
print("x1 =", result[0])
print("x2 =", result[1])
print("x3 =", result[2])


Matriks A:
[[5 1 1]
 [1 5 1]
 [1 1 5]]

Vektor B:
[7 7 7]

Solusi SPL:
x1 = 1.0
x2 = 1.0
x3 = 0.9999999999999998
